### ISSUE TITLE
Opentelemetry-runtime-attach does not export to Jaeger 

### ISSUE THREAD

**Issue by bjeSSAdev** [open-telemetry/opentelemetry-java-contrib#1216]
### Component(s)

runtime-attach

## Description
When using the opentelemetry-runtime-attach library , it fails at start up when OTEL_TRACES_EXPORTER=jaeger.  The message is 
## Steps to Reproduce
Add the library depedency 
`<dependency>
			<groupId>io.opentelemetry.contrib</groupId>
			<artifactId>opentelemetry-runtime-attach</artifactId>
			<version>1.33.0-alpha</version>
		</dependency>`

Update the main method as follows:

`
    public static void main(String[] args) {
        RuntimeAttach.attachJavaagentToCurrentJvm();
        SpringApplication.run(DemoApplication.class, args);
    }
`

and set OTEL_TRACES_EXPORTER=jaeger.

## Expected Result

Opentelemetry java agent starts up normally as well as the application.

# Actual Result
Opentelemetry java agent fails to start , however the the application starts normally.

### Component version

1.33.0-alpha

### Log output

[otel.javaagent 2024-03-07 11:23:11:484 -0500] [Attach Listener] INFO io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdkBuilder - Error encountered during autoconfiguration. Closing partially configured components.
OpenTelemetry Javaagent failed to start
io.opentelemetry.sdk.autoconfigure.spi.ConfigurationException: otel.traces.exporter set to "jaeger" but opentelemetry-exporter-jaeger not found on classpath. Make sure to add it as a dependency.
	at io.opentelemetry.sdk.autoconfigure.SpanExporterConfiguration.configureExporter(SpanExporterConfiguration.java:95)
	at io.opentelemetry.sdk.autoconfigure.SpanExporterConfiguration.configureSpanExporters(SpanExporterConfiguration.java:67)
	at io.opentelemetry.sdk.autoconfigure.TracerProviderConfiguration.configureTracerProvider(TracerProviderConfiguration.java:55)
	at io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdkBuilder.build(AutoConfiguredOpenTelemetrySdkBuilder.java:416)
	at io.opentelemetry.javaagent.tooling.OpenTelemetryInstaller.installOpenTelemetrySdk(OpenTelemetryInstaller.java:29)
	at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:123)
	at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:103)
	at io.opentelemetry.javaagent.tooling.AgentStarterImpl.start(AgentStarterImpl.java:99)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer$1.run(AgentInitializer.java:53)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer$1.run(AgentInitializer.java:47)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.execute(AgentInitializer.java:64)
	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:46)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.startAgent(OpenTelemetryAgent.java:57)
	at io.opentelemetry.javaagent.OpenTelemetryAgent.agentmain(OpenTelemetryAgent.java:49)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:491)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:513)

### Additional context

I believe the issue is the Jaeger exporter is not package into the otel-agent.jar.

**Comment by trask** [comment]
hi @bjeSSAdev! the jaeger exporter was deprecated previously, and removed in https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.33.0

**Comment by trask** [comment]
see also https://opentelemetry.io/blog/2022/jaeger-native-otlp/

**Comment by bjeSSAdev** [comment]
Ahh thanks I missed that.
