### ISSUE TITLE
Sending JFR RecordingOptions with a diagnostic command may fail on Java 8 

### ISSUE THREAD

**Issue by dsgrieve** [open-telemetry/opentelemetry-java-contrib#1338]
### Component(s)

jfr-connection

## Description
Time based recording options (time and age) are sent with a space between the value and units, e.g. "6000 ms", which may cause an issue with Java 8/Diagnostic Command.

## Steps to Reproduce
Create an application with FlightRecorderDiagnosticCommandConnection which sets the 'time' or 'age' option for a recording. This causes an issue with Oracle Java 8. 

## Expected Result
No exception returned from the diagnostic command mbean. 

### Component version

1.36.0

### Log output

com.microsoft.jfr.JfrStreamingException: Java 8 currently only supports predefined configurations (default/profile)
      at com.microsoft.jfr.dcmd.FlightRecorderDiagnosticCommandConnection.formOptions(FlightRecorderDiagnosticCommandConnection.java:135)
      at com.microsoft.jfr.dcmd.FlightRecorderDiagnosticCommandConnection.startRecording(FlightRecorderDiagnosticCommandConnection.java:109)
      at com.microsoft.jfr.Recording.start(Recording.java:116)

### Additional context

This is an issue that was reported by a third party using the com.microsoft:jfr-streaming classes, which is where jfr-connection comes from. So this issue is present in jfr-connection as well. This issue won't be fixed in com.microsoft:jfr-streaming since that code is no longer maintained.

**Comment by dsgrieve** [comment]
```bash
ERROR c.m.a.a.internal.profiler.Profiler - Internal JFR Error
com.microsoft.jfr.JfrStreamingException: Java 8 currently only supports predefined configurations (default/profile)
      at com.microsoft.jfr.dcmd.FlightRecorderDiagnosticCommandConnection.formOptions(FlightRecorderDiagnosticCommandConnection.java:135)
```
 
This is an exception thrown explicitly from FlightRecorderDiagnosticCommandConnection which implies the caller is most likely trying to use a MapConfiguration to set the recording configuration and this is not an issue with a space between the duration and units in the recording options. It seems to me the issue might just be that the code should log an error rather than throwing an exception here.

**Comment by dsgrieve** [comment]
PR https://github.com/open-telemetry/opentelemetry-java-contrib/pull/1352
