### ISSUE TITLE
ConsistentReservoirSamplingSpanProcessorTest is sporadically failing

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-contrib#1602]
https://github.com/open-telemetry/opentelemetry-java-contrib/actions/runs/12319968072/job/34388221769

(the reason this didn't show up before is because we used to auto-retry tests)

```
> Task :consistent-sampling:test

ConsistentReservoirSamplingSpanProcessorTest > testConsistentSampling() FAILED
    java.lang.AssertionError: 
    Expecting actual:
      0.006596909041848287
    to be greater than:
      0.01
        at io.opentelemetry.contrib.sampler.consistent.TestUtil.verifyObservedPvaluesUsingGtest(TestUtil.java:72)
        at io.opentelemetry.contrib.sampler.consistent.ConsistentReservoirSamplingSpanProcessorTest.testConsistentSampling(ConsistentReservoirSamplingSpanProcessorTest.java:608)
        at io.opentelemetry.contrib.sampler.consistent.ConsistentReservoirSamplingSpanProcessorTest.testConsistentSampling(ConsistentReservoirSamplingSpanProcessorTest.java:663)
```

**Comment by trask** [comment]
@oertl @PeterF778 could you look at this? we're still seeing fairly regular sporadic test failures, see #1762

**Comment by oertl** [comment]
This statistical test may sporadically fail if the result depends on randomness. The seeds for the random generators used by the ConsistentReservoirSamplingSpanProcessor are set in the test. However, it seems that the spans get processed in different orders for some reason, which causes some variations.

**Comment by oertl** [comment]
It is fine to temporarily disable the test. I would have to find some more time to investigate, as these variations are not caused by the sampling part.
