### ISSUE TITLE
HBaseIntegrationTest is sporadically failing

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-contrib#1605]
https://github.com/open-telemetry/opentelemetry-java-contrib/actions/runs/12323227431/job/34402775016?pr=1603

(the reason this didn't show up before is because we used to auto-retry tests)

```
> Task :jmx-scraper:integrationTest

HBaseIntegrationTest > endToEndTest(Path) FAILED
    org.opentest4j.AssertionFailedError: [no data point matched attribute set '[{state=compaction}, {region_server}]' for metric 'hbase.region_server.queue.length'] 
    expected: true
     but was: false
        at app//io.opentelemetry.contrib.jmxscraper.assertions.MetricAssert.lambda$hasDataPointsWithAttributes$2(MetricAssert.java:262)
        at app//io.opentelemetry.contrib.jmxscraper.assertions.MetricAssert.checkDataPoints(MetricAssert.java:188)
        at app//io.opentelemetry.contrib.jmxscraper.assertions.MetricAssert.hasDataPointsWithAttributes(MetricAssert.java:231)
        at app//io.opentelemetry.contrib.jmxscraper.target_systems.HBaseIntegrationTest.lambda$createMetricsVerifier$9(HBaseIntegrationTest.java:126)
```

**Comment by SylvainJuge** [comment]
For reference the flaky tests retry has been removed in https://github.com/open-telemetry/opentelemetry-java-contrib/pull/1567 because it relied on develocity.

**Comment by trask** [comment]
we can bring back test retry, but we no longer have access to see flaky tests across builds, and so the concern is that we won't see them at all

in the instrumentation repo we mitigated this a bit by only removing retries on the daily builds, so the flaky tests will still bubble up to us on the daily builds

if flaky tests become enough of a problem in this repo we can do the same

**Comment by SylvainJuge** [comment]
As discussed today with @robsunday today, we think most of those test failures tend to be related to some JMX Beans not being published/ready, and it will need some case-by-case investigation, so for now we think increasing the timeout would probably help mitigate that in the short term, for example with #1612.
