### ISSUE TITLE
Test flake in :sdk-extensions:aws

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java-contrib#507]
`SimpleHttpClientTest` [failed](https://github.com/open-telemetry/opentelemetry-java/runs/7981631151?check_suite_focus=true) with:
```
SimpleHttpClientTest$HttpsServerTest > goodCert() FAILED
    org.opentest4j.AssertionFailedError: 
    expected: "Thanks for trusting me"
     but was: ""
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at io.opentelemetry.sdk.extension.aws.resource.SimpleHttpClientTest$HttpsServerTest.goodCert(SimpleHttpClientTest.java:84)
```

**Comment by mateuszrzeszutek** [comment]
@willarmiros can you take a look at this?

**Comment by trask** [comment]
Closing, we've implemented retry for now to avoid CI failures, and we can use #890 to drive down flaky tests (once it's implemented).
